name: "Generate Terraform graph"
on:
  workflow_call:

jobs:
  terraform:
    name: "Generate Terraform graph"
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: test
        run: pwd

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: 1.3.7
          terraform_wrapper: false

      - name: Terraform Init
        run: "terraform init -input=false -no-color"

      - name: Install graphviz
        run: "sudo apt-get install -y graphviz"

      - name: Terraform Graph
        id: graph
        run: terraform graph > graph.dot

      - name: Convert Graph to SVG
        id: graph_convert
        run: dot -Tsvg graph.dot > graph.svg

      - name: Push changes back to PR branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update graph.svg"
          file_pattern: graph.svg
